version: "3.8"
secrets:
  JWT_SECRET:
    file: ../.secrets/authelia/JWT_SECRET
  SESSION_SECRET:
    file: ../.secrets/authelia/SESSION_SECRET
  STORAGE_PASSWORD:
    file: ../.secrets/authelia/STORAGE_PASSWORD
  STORAGE_ENCRYPTION_KEY:
    file: ../.secrets/authelia/STORAGE_ENCRYPTION_KEY
  LDAP_PASSWORD: 
    file: ../.secrets/authelia/LDAP_PASSWORD
  SMTP_PASSWORD: 
    file: ../.secrets/authelia/SMTP_PASSWORD

services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    networks:
      - authelia_frontend
      - psql_backend
      - ldap_backend
    expose:
      - 9091
    secrets: [JWT_SECRET, SESSION_SECRET, STORAGE_PASSWORD, STORAGE_ENCRYPTION_KEY, LDAP_PASSWORD, SMTP_PASSWORD]
    environment:
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/SESSION_SECRET
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /run/secrets/STORAGE_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /run/secrets/LDAP_PASSWORD
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/SMTP_PASSWORD
    volumes:
      - ./config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.rule: Host(`login.jomer.dev`)      
      traefik.http.routers.authelia.entrypoints: websecure
      traefik.http.routers.authelia.tls.certresolver: letsencrypt
      traefik.http.services.authelia.loadbalancer.server.port: 9091
      traefik.docker.network: authelia_frontend

      traefik.http.middlewares.authelia.forwardAuth.address: http://authelia:9091/api/verify?rd=https%3A%2F%2Flogin.jomer.dev%2F
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: true
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
      traefik.http.middlewares.authelia-basic.forwardAuth.address: http://authelia:9091/api/verify?auth=basic
      traefik.http.middlewares.authelia-basic.forwardAuth.trustForwardHeader: true
      traefik.http.middlewares.authelia-basic.forwardAuth.authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email

networks:
    authelia_frontend:
        name: authelia_frontend
    psql_backend:
        external: true
    ldap_backend:
        external: true
